# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76dd0b8584221fd55ed7351f2550c5d88665ce463b50c91be528ef4c6b03b722a306edb1931ac8a8a18dc16428abf82594a9f28659de55902af4e7e7b02729af

test:
  secret_key_base: bb63b363fa29c5f3f4d2aa1093c1445fae8ceb2b8997459aadd482da8c1e14890ee94df453836f5d372075c65195165da59164b8be1881cc25ed63f2c5df9406

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
